sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx6a945c030a44568f
    secret: 9168c23bcb957df5e412ffb3badb3c46
